version: '3.8'

services:
  lb:
    container_name: kc_lb
    image: nginx:1.24.0
    volumes:
      - /Users/snaya/Matching/lb/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  kc1:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: kc1
    command:
      - start-dev
    ports:
      - ${FORWARD_KC1_PORT}:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_DATABASE: ${KC_DB_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_PROXY: edge
    depends_on:
      lb:
        condition: service_started

  kc2:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: kc2
    command: 
      - start-dev
    ports:
      - ${FORWARD_KC2_PORT}:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_DATABASE: ${KC_DB_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_PROXY: edge
    depends_on:
      lb:
        condition: service_started

  mariadb:
    image: mariadb:10
    container_name: kc_db
    ports:
      - ${FORWARD_KC_DB_PORT}:3306
    volumes:
      - /Users/snaya/Matching/db/custom.cnf:/etc/mysql/conf.d/my.cnf
      - /Users/snaya/Matching/constellation/SQL/keycloak.sql:/docker-entrypoint-initdb.d/initDb.sql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ${KC_DB_DATABASE}
      MARIADB_USER: ${KC_DB_USER}
      MARIADB_PASSWORD: ${KC_DB_PASSWORD}
      TZ: ${TZ}

  mariadb_2:
    image: mariadb:10
    container_name: app_db
    ports:
      - ${FORWARD_APP_DB_PORT}:3306
    volumes:
      - /Users/snaya/Matching/app_data:/var/lib/mysql
      - /Users/snaya/Matching/custom.cnf:/etc/mysql/conf.d/my.cnf
      - /Users/snaya/Matching/constellation/SQL/const.sql:/docker-entrypoint-initdb.d/initDb.sql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ${APP_DB_DATABASE}
      MARIADB_USER: ${APP_DB_USER}
      MARIADB_PASSWORD: ${APP_DB_PASSWORD}
      TZ: ${TZ}

  constellation_match:
    image: matching:0.1
    container_name: constellation_match
    ports:
      - 8000:8000
    volumes:
      - ./constellation:/app
    depends_on:
      - mariadb_2